### ISSUE TITLE
EllipticCurveAdd fails when aIsInfinity == 1

### ISSUE THREAD

**Issue by Dimo99** [yi-sun/circom-pairing#12]
I tried to use EllipticCurveAdd for aggregating public keys but found that it fails when `aIsInfinity == 1` and the point a is at infinity.
I tried to log a few things and I suspect the problem comes from this line https://github.com/yi-sun/circom-pairing/blob/743d761f07254ea6407d29ba05f29886cfd14aec/circuits/curve.circom#L340
Where the point at infinity is doubled.

**Comment by Dimo99** [comment]
For now, I think I solved my problem by removing this thing. As for aggregating public keys, I don't need the double I think. Though I am not sure if this is 100% correct

**Comment by jonathanpwang** [comment]
In your test case, is it (incorrectly) returning that `out` is infinity? 
The intended logic is that `doub` should be ignored if `aIsInfinity == 1`.

**Comment by Dimo99** [comment]
It just throws an error when I calculate the witness. 
This is the error I get
```
Error: Error: Assert Failed. Error in template Num2Bits_40 line: 38
```
I am ussing `[[1, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0]] ` for point at inifinity

**Comment by jonathanpwang** [comment]
Ah - due to the deterministic nature of circuits, even when `aIsInfinity == 1`, the usage of the circuit requires that `a` is a point on the curve (you can put in a random point, as long as it is on `E`). (See documentation: https://github.com/yi-sun/circom-pairing/tree/master/docs#ellipticcurveaddn-k-p).

Does that solve your issue?

**Comment by Dimo99** [comment]
Yes, it does. Thanks
